# Generated by Django 4.1.5 on 2023-01-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=150)),
                ('imge', models.ImageField(upload_to='picture')),
                ('descr', models.TextField()),
            ],
        ),
    ]
